import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { AppPhoto } from 'src/app/shared/models/photo.model';

@Injectable({
  providedIn: 'root'
})
export class StateService {
  compte$= new BehaviorSubject<any>({
    solde : 31162,
    transactions: [
      {
        title: 'Commission',
        date: '01/02/2023',
        amount: 1262,
        type: 'commission',
        currency: 'XAF'
      },
      {
        title: 'Retrait',
        date: '28/01/2023',
        amount: 25000,
        type: 'debit',
        currency: 'XAF',
      },
      {
        title: 'Versement',
        date: '14/01/2023',
        amount: 2000,
        type: 'credit',
        currency: 'XAF',
      },
      {
        title: 'Versement',
        date: '04/01/2023',
        amount: 2000,
        type: 'credit',
        currency: 'XAF',
      },
      {
        title: 'Versement',
        date: '03/01/2023',
        amount: 2000,
        type: 'credit',
        currency: 'XAF',
      }        
      
    ]
  });

  clients$ = new BehaviorSubject<any[]>([
    {
      "id": 1,
      "dateCreation": null,
      "nom": "MONGOU KENTSOP ROCHINEL",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": 653218531,
      "matricule": 110,
      "photo": ""
    },
    {
      "id": 2,
      "dateCreation": null,
      "nom": "NGUETSOP T ",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 3,
      "dateCreation": 44398,
      "nom": "TOUKAM WAFO D'AQUIN",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 4,
      "dateCreation": null,
      "nom": "ALEMDJOU NANFACK",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "COMMERCANTE",
      "cni": "108613947",
      "telephone": 654473502,
      "matricule": 358,
      "photo": ""
    },
    {
      "id": 5,
      "dateCreation": null,
      "nom": "AMANDJOU CHRITELLE ROSINE BONONO OLITTE EPSE EDZI",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 6,
      "dateCreation": null,
      "nom": "ANATEU JUBERINE MIREILLE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 35,
      "photo": ""
    },
    {
      "id": 7,
      "dateCreation": null,
      "nom": "ANOUDEM SAMUEL",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 8,
      "dateCreation": null,
      "nom": "ASAHGWO",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 9,
      "dateCreation": null,
      "nom": "ATANGANA  EYEBE JOACHIM",
      "sexe": "M",
      "localisation": "MENDONG",
      "activite": "",
      "cni": "KIT 329",
      "telephone": 657300606,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 10,
      "dateCreation": null,
      "nom": "ATEALAH",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 11,
      "dateCreation": null,
      "nom": "AWOUNANG ANNE MIREILLE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 127,
      "photo": ""
    },
    {
      "id": 12,
      "dateCreation": null,
      "nom": "AZAMBOU TSAGO MYLENE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 13,
      "dateCreation": null,
      "nom": "AZEBAZE PULCHERIE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 14,
      "dateCreation": null,
      "nom": "BAANA CHRISTINE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 66,
      "photo": ""
    },
    {
      "id": 15,
      "dateCreation": null,
      "nom": "BANEM CHRISTELLE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 16,
      "dateCreation": null,
      "nom": "BEHALAL  JOSEPH",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 17,
      "dateCreation": null,
      "nom": "BEDJA",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 18,
      "dateCreation": null,
      "nom": "BELIBI BELIBI OTTO JEAN",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 19,
      "dateCreation": null,
      "nom": "BELIBI CHRISTIAN",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 28,
      "photo": ""
    },
    {
      "id": 20,
      "dateCreation": null,
      "nom": "BONG LAURA MAIH",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 21,
      "dateCreation": null,
      "nom": "BOUZANG JIOTSOP",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 22,
      "dateCreation": null,
      "nom": "NGUIDJOL",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 23,
      "dateCreation": null,
      "nom": "CHIOZEM DONGMO ELISE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 24,
      "dateCreation": null,
      "nom": "CHOUMELE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 47,
      "photo": ""
    },
    {
      "id": 25,
      "dateCreation": null,
      "nom": "NGUIMFACK R",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 26,
      "dateCreation": null,
      "nom": "DENTOU JOSEPH",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 27,
      "dateCreation": null,
      "nom": "DEUTOU MELANIE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 125,
      "photo": ""
    },
    {
      "id": 28,
      "dateCreation": null,
      "nom": "DIFFO KEMO ",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 29,
      "dateCreation": null,
      "nom": " NGATHA EPSE NOUTCHA HORTANCE",
      "sexe": "F",
      "localisation": "ZIBI",
      "activite": "DIRECTRICE",
      "cni": "378794",
      "telephone": 672701084,
      "matricule": 128,
      "photo": ""
    },
    {
      "id": 30,
      "dateCreation": null,
      "nom": "ZIBI",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 31,
      "dateCreation": null,
      "nom": "FEUDJIO KENTSA",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 32,
      "dateCreation": null,
      "nom": "DJOFANG MELANIE OU JAGOU",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "COIFFEUSE",
      "cni": "118405443",
      "telephone": 674001551,
      "matricule": 132,
      "photo": ""
    },
    {
      "id": 33,
      "dateCreation": null,
      "nom": "DJOUKOUO FOSSI ",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 34,
      "dateCreation": null,
      "nom": "DJOUMENE INNOCENT",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 75,
      "photo": ""
    },
    {
      "id": 35,
      "dateCreation": null,
      "nom": "ZEUKENG TONGO",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 36,
      "dateCreation": null,
      "nom": "DONFACK EMILIE DORINE 2",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "COIFFEUSE",
      "cni": "",
      "telephone": 678075468,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 37,
      "dateCreation": null,
      "nom": "DONFACK JIEFACK BENSON",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 38,
      "dateCreation": null,
      "nom": "DONGMEZA FRANC 2",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 39,
      "dateCreation": null,
      "nom": "DONGMO ALOIS",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 40,
      "dateCreation": null,
      "nom": "DONGMO DAVID",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 41,
      "dateCreation": null,
      "nom": "DONGMO JIOGUE BILLY D",
      "sexe": "M",
      "localisation": "ECOLE PUBLIQUE MENDONG",
      "activite": "ELEVE",
      "cni": "",
      "telephone": 695606058,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 42,
      "dateCreation": null,
      "nom": "DONGMO MAINA",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 43,
      "dateCreation": null,
      "nom": "DONGMO MARIE SUZANNE OU KAAFACK KOUTSING JOSEPH OU DONGMO KAAFACK IDERLINE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 25,
      "photo": ""
    },
    {
      "id": 44,
      "dateCreation": null,
      "nom": "DONGMO NGUIMAPI ALBERT FRANCIS OU GOUGNI LEMOKEN CALISTE",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 45,
      "dateCreation": null,
      "nom": "DOUALA MAURICE",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 46,
      "dateCreation": null,
      "nom": "DOUANLA ETIENNE",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 47,
      "dateCreation": null,
      "nom": "GOUGNI LEMOKEM CALISTE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 48,
      "dateCreation": null,
      "nom": "ABEGA MARTIN JOEL",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 49,
      "dateCreation": null,
      "nom": "TSAFACK NADEGE CLAIRE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 50,
      "dateCreation": null,
      "nom": "KENDZEU MARIE GISELE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 51,
      "dateCreation": null,
      "nom": "LIKANE ERIC GEORGES",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 52,
      "dateCreation": null,
      "nom": "JAGOU SOLEIL",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 53,
      "dateCreation": null,
      "nom": "NGOUFO TCHINO MODESTE",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 8,
      "photo": ""
    },
    {
      "id": 54,
      "dateCreation": null,
      "nom": "DJELE WILLIAM",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 9,
      "photo": ""
    },
    {
      "id": 55,
      "dateCreation": null,
      "nom": "NGUIMGO GEORGETTE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 10,
      "photo": ""
    },
    {
      "id": 56,
      "dateCreation": null,
      "nom": "KEMDA MAJOUH BELLO 1",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 11,
      "photo": ""
    },
    {
      "id": 57,
      "dateCreation": null,
      "nom": "TSAMO PASCAL",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "COMMERCANT",
      "cni": "116956184",
      "telephone": 679014949,
      "matricule": 591,
      "photo": ""
    },
    {
      "id": 58,
      "dateCreation": null,
      "nom": "TIAGUEU ERMINE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 14,
      "photo": ""
    },
    {
      "id": 59,
      "dateCreation": null,
      "nom": "NGO NONDENG VIRGINIE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 15,
      "photo": ""
    },
    {
      "id": 60,
      "dateCreation": null,
      "nom": "FEUDJIO KENFO JEAN YACIN",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 16,
      "photo": ""
    },
    {
      "id": 61,
      "dateCreation": null,
      "nom": "NGUEKENG OCTALANIE ALEX OU KENFACK RONIE",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 17,
      "photo": ""
    },
    {
      "id": 62,
      "dateCreation": null,
      "nom": "TEZEM BOREL OU FOMENA GILDAS",
      "sexe": "M",
      "localisation": "SIMBOCK",
      "activite": "LAVEUR",
      "cni": "495289",
      "telephone": 662175230,
      "matricule": 18,
      "photo": ""
    },
    {
      "id": 63,
      "dateCreation": null,
      "nom": "KENNE OLIVIER",
      "sexe": "M",
      "localisation": "SIMBOCK",
      "activite": "MECANICIEN",
      "cni": "",
      "telephone": null,
      "matricule": 19,
      "photo": ""
    },
    {
      "id": 64,
      "dateCreation": null,
      "nom": "MASSAH TSOPMEDJIO BERTIN",
      "sexe": "M",
      "localisation": "ENTREE SIMBOCK",
      "activite": "COMMERCANT",
      "cni": "13824",
      "telephone": 679273803,
      "matricule": 460,
      "photo": ""
    },
    {
      "id": 65,
      "dateCreation": null,
      "nom": "NGUEPI JEAN BOSCO",
      "sexe": "M",
      "localisation": "MENDONG",
      "activite": "",
      "cni": "112231761",
      "telephone": 677301518,
      "matricule": 21,
      "photo": ""
    },
    {
      "id": 66,
      "dateCreation": null,
      "nom": "TATSA HONORE",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 23,
      "photo": ""
    },
    {
      "id": 67,
      "dateCreation": null,
      "nom": "FEUJIO CLEMENTINE OU MEGANG EMILIE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "110330177",
      "telephone": 674541467,
      "matricule": 25,
      "photo": ""
    },
    {
      "id": 68,
      "dateCreation": null,
      "nom": "DONFACK EMILIE DORINE 1",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "COIFFEUSE",
      "cni": "346654",
      "telephone": 671748258,
      "matricule": 26,
      "photo": ""
    },
    {
      "id": 69,
      "dateCreation": null,
      "nom": "TSOPZE AGATHE MARIE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 27,
      "photo": ""
    },
    {
      "id": 70,
      "dateCreation": null,
      "nom": "NGUIMATSA N°2",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 29,
      "photo": ""
    },
    {
      "id": 71,
      "dateCreation": null,
      "nom": "METIONOUGNI CECILE OU NANTIA FOKOU",
      "sexe": "F",
      "localisation": "TKC",
      "activite": "MENAGERE",
      "cni": "109762193",
      "telephone": 674271007,
      "matricule": 31,
      "photo": ""
    },
    {
      "id": 72,
      "dateCreation": null,
      "nom": "LANGOUO MARTIN",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 33,
      "photo": ""
    },
    {
      "id": 73,
      "dateCreation": null,
      "nom": "FAMOU KELLY FLORE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 34,
      "photo": ""
    },
    {
      "id": 74,
      "dateCreation": null,
      "nom": "GUEGUIM LEMOKEM JORDAN BRONDON",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 36,
      "photo": ""
    },
    {
      "id": 75,
      "dateCreation": null,
      "nom": "NGUM E",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 37,
      "photo": ""
    },
    {
      "id": 76,
      "dateCreation": null,
      "nom": "DEMEZEH KEUNKEM EPSE ZEBAZE COLORINCE",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "11432844",
      "telephone": 699882022,
      "matricule": 40,
      "photo": ""
    },
    {
      "id": 77,
      "dateCreation": null,
      "nom": "TSAFACK BERNARD",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 41,
      "photo": ""
    },
    {
      "id": 78,
      "dateCreation": null,
      "nom": "KEMDA MAJOUH BELLO 2",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 42,
      "photo": ""
    },
    {
      "id": 79,
      "dateCreation": null,
      "nom": "MBIA EPSE NGWA MWANJO ",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "1000726846",
      "telephone": 66164362,
      "matricule": 46,
      "photo": ""
    },
    {
      "id": 80,
      "dateCreation": null,
      "nom": "MAFFO JULIENNE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 49,
      "photo": ""
    },
    {
      "id": 81,
      "dateCreation": null,
      "nom": "FOGA GUECFACK CAROLE OU TIAGUEU ERMINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 51,
      "photo": ""
    },
    {
      "id": 82,
      "dateCreation": null,
      "nom": "FEUDJIIO PELAGIE",
      "sexe": "F",
      "localisation": "TKC",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 52,
      "photo": ""
    },
    {
      "id": 83,
      "dateCreation": null,
      "nom": "SOKOUBO LUCAS",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "VENDEUR",
      "cni": "110316602",
      "telephone": 676673544,
      "matricule": 1037,
      "photo": ""
    },
    {
      "id": 84,
      "dateCreation": null,
      "nom": "KOUATCHIC ROMEO",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "MECANICIEN",
      "cni": "1087295802",
      "telephone": 679805433,
      "matricule": 52,
      "photo": ""
    },
    {
      "id": 85,
      "dateCreation": null,
      "nom": "NDJUMEGUE REGINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "108123883",
      "telephone": 676055339,
      "matricule": 56,
      "photo": ""
    },
    {
      "id": 86,
      "dateCreation": null,
      "nom": "MAWAMBA JEANNE FLORE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "vendeuse",
      "cni": "107847040",
      "telephone": 675034156,
      "matricule": 346,
      "photo": ""
    },
    {
      "id": 87,
      "dateCreation": null,
      "nom": "SOBJIO EPSE  GUEPI EUPHRASIE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "109570401",
      "telephone": 694975439,
      "matricule": 61,
      "photo": ""
    },
    {
      "id": 88,
      "dateCreation": null,
      "nom": "TSAFACK TSAGMO ZANDJEU EVELINE LORD OU NAFACK KEVINE OU SONKENG HEMART ARMANDINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "COUTURIERE",
      "cni": "100886514",
      "telephone": 677731807,
      "matricule": 62,
      "photo": ""
    },
    {
      "id": 89,
      "dateCreation": null,
      "nom": "MBOUEDEU NGANGOUE",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 64,
      "photo": ""
    },
    {
      "id": 90,
      "dateCreation": null,
      "nom": "NJUITAPVOUI MIMCHE",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 72,
      "photo": ""
    },
    {
      "id": 91,
      "dateCreation": null,
      "nom": "TALLA FEUDJIO ROMARIC",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "MECANICIEN",
      "cni": "KIT329",
      "telephone": null,
      "matricule": 73,
      "photo": ""
    },
    {
      "id": 92,
      "dateCreation": null,
      "nom": "FOMEDJIO SANFO GILDAS ",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "SOUDEUR",
      "cni": "1002000856",
      "telephone": 674369802,
      "matricule": 79,
      "photo": ""
    },
    {
      "id": 93,
      "dateCreation": null,
      "nom": "TIOMENA KENNE FRANCKY VALEX",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "114300305",
      "telephone": 680804513,
      "matricule": 86,
      "photo": ""
    },
    {
      "id": 94,
      "dateCreation": null,
      "nom": "MINTOUNOU MVOGO CAROLLE ROSE ",
      "sexe": "F",
      "localisation": "TKC",
      "activite": "",
      "cni": "108908137",
      "telephone": null,
      "matricule": 87,
      "photo": ""
    },
    {
      "id": 95,
      "dateCreation": null,
      "nom": "KENFACK THIERRY JOEL",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "LAVEUR",
      "cni": "110354318",
      "telephone": 674537864,
      "matricule": 89,
      "photo": ""
    },
    {
      "id": 96,
      "dateCreation": null,
      "nom": "MBOGNI JACQUES COLLINS",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "",
      "cni": "",
      "telephone": 675329620,
      "matricule": 92,
      "photo": ""
    },
    {
      "id": 97,
      "dateCreation": null,
      "nom": "TIOKENG GERADINE",
      "sexe": "F",
      "localisation": "TKC",
      "activite": "",
      "cni": "KIT067",
      "telephone": 650795070,
      "matricule": 94,
      "photo": ""
    },
    {
      "id": 98,
      "dateCreation": null,
      "nom": "NGUEDIA NOUMEDEM JEAN MARIE",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "",
      "cni": "109142217",
      "telephone": 673617787,
      "matricule": 96,
      "photo": ""
    },
    {
      "id": 99,
      "dateCreation": null,
      "nom": "NGUEKENG OCTALANIE ALEX N°1",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 103,
      "photo": ""
    },
    {
      "id": 100,
      "dateCreation": 43473,
      "nom": "YOGAM ETIENNE YUBUINWA",
      "sexe": "M",
      "localisation": "ENTREE SIMBOCK",
      "activite": "VENDEUR",
      "cni": "CE0067I5ISZAI0CM004",
      "telephone": 653840099,
      "matricule": 701403,
      "photo": ""
    },
    {
      "id": 101,
      "dateCreation": null,
      "nom": "SOFACK NJOUFACK EDITH OU  NGOUNI LEMOKEM CALISTE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": 673951631,
      "matricule": 108,
      "photo": ""
    },
    {
      "id": 102,
      "dateCreation": null,
      "nom": "FOKOU MATHIEU",
      "sexe": "M",
      "localisation": "ENTREE SIMBOCK",
      "activite": "",
      "cni": "",
      "telephone": 676554727,
      "matricule": 112,
      "photo": ""
    },
    {
      "id": 103,
      "dateCreation": null,
      "nom": "MBENA BELINGA JACQUELINE",
      "sexe": "F",
      "localisation": "TKC",
      "activite": "",
      "cni": "",
      "telephone": 697178124,
      "matricule": 120,
      "photo": ""
    },
    {
      "id": 104,
      "dateCreation": null,
      "nom": "FOUEDJI LUCIE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 105,
      "dateCreation": null,
      "nom": "KENFACK JOSEPHINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": 653894049,
      "matricule": 122,
      "photo": ""
    },
    {
      "id": 106,
      "dateCreation": null,
      "nom": "TEMATIO FRANCOISE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "289371",
      "telephone": 675418560,
      "matricule": 128,
      "photo": ""
    },
    {
      "id": 107,
      "dateCreation": null,
      "nom": "CHO  MARCELINE SHIRE",
      "sexe": "F",
      "localisation": "TKC",
      "activite": "",
      "cni": "115691292",
      "telephone": 674681121,
      "matricule": 130,
      "photo": ""
    },
    {
      "id": 108,
      "dateCreation": null,
      "nom": "NGUENA SAMUEL",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": 674279361,
      "matricule": 135,
      "photo": ""
    },
    {
      "id": 109,
      "dateCreation": null,
      "nom": "NKOUAYEP FIRMIN ROMEO",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUR",
      "cni": "110091719",
      "telephone": 682962041,
      "matricule": 136,
      "photo": ""
    },
    {
      "id": 110,
      "dateCreation": null,
      "nom": "OTOMO ISABELLE CHRISTELLE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "vendeuse",
      "cni": "116877331",
      "telephone": 671892310,
      "matricule": 256,
      "photo": ""
    },
    {
      "id": 111,
      "dateCreation": null,
      "nom": "TIOFACK JEAN RENE",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": 670560510,
      "matricule": 139,
      "photo": ""
    },
    {
      "id": 112,
      "dateCreation": null,
      "nom": "MBIN MICHEL",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": 679933704,
      "matricule": 140,
      "photo": ""
    },
    {
      "id": 113,
      "dateCreation": null,
      "nom": "ZEFACK DZEUFOUO SIDONIE OU DJUIKA",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": 695622881,
      "matricule": 140,
      "photo": ""
    },
    {
      "id": 114,
      "dateCreation": null,
      "nom": "KEMTA RUBEN",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "",
      "cni": "",
      "telephone": 672344801,
      "matricule": 141,
      "photo": ""
    },
    {
      "id": 115,
      "dateCreation": null,
      "nom": "LATTA JOSEPH",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "",
      "cni": "KIT 329",
      "telephone": 675128779,
      "matricule": 142,
      "photo": ""
    },
    {
      "id": 116,
      "dateCreation": null,
      "nom": "DJIOFACK EPSE TEZO JOSIANE",
      "sexe": "F",
      "localisation": "DERRIERE LE CAMP",
      "activite": "MENAGERE",
      "cni": "110354196",
      "telephone": 699610822,
      "matricule": 143,
      "photo": ""
    },
    {
      "id": 117,
      "dateCreation": null,
      "nom": "TOUKEM CHARLOTTE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 138,
      "photo": ""
    },
    {
      "id": 118,
      "dateCreation": null,
      "nom": "EMNGUE BENOIT OU NGOUGNI",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 125,
      "photo": ""
    },
    {
      "id": 119,
      "dateCreation": null,
      "nom": "KETCHANJI VALENTIN",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUR",
      "cni": "KIT067",
      "telephone": 673888967,
      "matricule": 126,
      "photo": ""
    },
    {
      "id": 120,
      "dateCreation": null,
      "nom": "NGUEDIA SAA ROMEO",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "MECANICIEN",
      "cni": "109399869",
      "telephone": 675324491,
      "matricule": 147,
      "photo": ""
    },
    {
      "id": 121,
      "dateCreation": null,
      "nom": "TEUMENA VICTOR",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUR",
      "cni": "115084301",
      "telephone": 662083519,
      "matricule": 129,
      "photo": ""
    },
    {
      "id": 122,
      "dateCreation": null,
      "nom": "NGUEGANG NGUEKENG ",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 130,
      "photo": ""
    },
    {
      "id": 123,
      "dateCreation": null,
      "nom": "WATSOP TAMMOUA DJUIKA EPSE TIOBO ROLANDE OU JOGO  JIONANG GLADYS",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "115634330",
      "telephone": null,
      "matricule": 131,
      "photo": ""
    },
    {
      "id": 124,
      "dateCreation": null,
      "nom": "MOULIOM AMADOU",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "BOUCHER",
      "cni": "487553",
      "telephone": 655081070,
      "matricule": 134,
      "photo": ""
    },
    {
      "id": 125,
      "dateCreation": null,
      "nom": "TCHINDA JUDITH IRENE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "CE0729315IMI2927BY",
      "telephone": 679659729,
      "matricule": 135,
      "photo": ""
    },
    {
      "id": 126,
      "dateCreation": null,
      "nom": "MAKEMZEM ANNIE  OU MANEDONG AKUIKEU DANNY RONEL",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "107817527",
      "telephone": 671949579,
      "matricule": 136,
      "photo": ""
    },
    {
      "id": 127,
      "dateCreation": null,
      "nom": "EYENGA JEAN",
      "sexe": "M",
      "localisation": "",
      "activite": "MOTA TAXI",
      "cni": "11691595",
      "telephone": 699933619,
      "matricule": 137,
      "photo": ""
    },
    {
      "id": 128,
      "dateCreation": null,
      "nom": "DJOMO ALINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "117703518",
      "telephone": 654026667,
      "matricule": 139,
      "photo": ""
    },
    {
      "id": 129,
      "dateCreation": null,
      "nom": "LONTSI VICTORINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "",
      "telephone": 673000573,
      "matricule": 140,
      "photo": ""
    },
    {
      "id": 130,
      "dateCreation": null,
      "nom": "METSOPNANG ALBERTINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "",
      "telephone": 656185767,
      "matricule": 142,
      "photo": ""
    },
    {
      "id": 131,
      "dateCreation": null,
      "nom": "YEMELE PIERRE ROGER",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "CHAUFFEUR",
      "cni": "",
      "telephone": 671008204,
      "matricule": 143,
      "photo": ""
    },
    {
      "id": 132,
      "dateCreation": null,
      "nom": "VOUKENG EVELYNE",
      "sexe": "F",
      "localisation": "SIMBOCK",
      "activite": "",
      "cni": "110442349",
      "telephone": null,
      "matricule": 146,
      "photo": ""
    },
    {
      "id": 133,
      "dateCreation": null,
      "nom": "KANA VICTOIRE",
      "sexe": "F",
      "localisation": "",
      "activite": "VENDEUSE",
      "cni": "",
      "telephone": 670822532,
      "matricule": 147,
      "photo": ""
    },
    {
      "id": 134,
      "dateCreation": null,
      "nom": "MEYE ANNE PULCHERIE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "COUTURIERE",
      "cni": "",
      "telephone": 693374055,
      "matricule": 148,
      "photo": ""
    },
    {
      "id": 135,
      "dateCreation": null,
      "nom": "KUEFOUET CLAUDE  MARTIAL",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUR",
      "cni": "",
      "telephone": 679117346,
      "matricule": 149,
      "photo": ""
    },
    {
      "id": 136,
      "dateCreation": null,
      "nom": "NGOUGNI BRIGITTE OU NGUIMDO EVELINE CHANTAL",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 151,
      "photo": ""
    },
    {
      "id": 137,
      "dateCreation": null,
      "nom": "KENFACK BRICE",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "VENDEUR",
      "cni": "",
      "telephone": 679798090,
      "matricule": 152,
      "photo": ""
    },
    {
      "id": 138,
      "dateCreation": null,
      "nom": "DONGMO SOFO CAREME OU  NOUGANG GEORGETTE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "",
      "telephone": 651052753,
      "matricule": 153,
      "photo": ""
    },
    {
      "id": 139,
      "dateCreation": null,
      "nom": "NGAHAN AMELIE JOLIE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUSE",
      "cni": "",
      "telephone": null,
      "matricule": 154,
      "photo": ""
    },
    {
      "id": 140,
      "dateCreation": null,
      "nom": "MAFFO DJAMPA JACQUELINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "COIFFEUSE",
      "cni": "",
      "telephone": null,
      "matricule": 157,
      "photo": ""
    },
    {
      "id": 141,
      "dateCreation": null,
      "nom": "GUESON BLAISE",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUR",
      "cni": "111095685",
      "telephone": 677847362,
      "matricule": 193,
      "photo": ""
    },
    {
      "id": 142,
      "dateCreation": null,
      "nom": "WAMBA TIOMELA FRANCIS",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": 678719380,
      "matricule": 159,
      "photo": ""
    },
    {
      "id": 143,
      "dateCreation": null,
      "nom": "KENGNE AMELINE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": 653954290,
      "matricule": 160,
      "photo": ""
    },
    {
      "id": 144,
      "dateCreation": null,
      "nom": "ABDUL KARIMO AZEVER",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "",
      "cni": "109489463",
      "telephone": null,
      "matricule": 162,
      "photo": ""
    },
    {
      "id": 145,
      "dateCreation": null,
      "nom": "DJEUFACK PAULINE",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "COUTURIERE",
      "cni": "110354217",
      "telephone": 696029192,
      "matricule": 595,
      "photo": ""
    },
    {
      "id": 146,
      "dateCreation": null,
      "nom": "DOUNTSOP TCHINDA JOSIANE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "113180362",
      "telephone": 672342893,
      "matricule": 165,
      "photo": ""
    },
    {
      "id": 147,
      "dateCreation": null,
      "nom": "FOUDJIO JEAN",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "83",
      "telephone": 674008227,
      "matricule": 167,
      "photo": ""
    },
    {
      "id": 148,
      "dateCreation": null,
      "nom": "NANTIA FOKOU DONALD",
      "sexe": "M",
      "localisation": "TKC",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": 169,
      "photo": ""
    },
    {
      "id": 149,
      "dateCreation": null,
      "nom": "AZANGUE AUGUSTIN OU FOUDJIO JEAN",
      "sexe": "M",
      "localisation": "MENDONG",
      "activite": "VENDEUR",
      "cni": "110640041",
      "telephone": 698284324,
      "matricule": 170,
      "photo": ""
    },
    {
      "id": 150,
      "dateCreation": null,
      "nom": "TSUALA CEDRIC",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUR",
      "cni": "114016109",
      "telephone": 676340862,
      "matricule": 171,
      "photo": ""
    },
    {
      "id": 151,
      "dateCreation": null,
      "nom": "CHOUTHDIGNIGNI ABDOU JALLILOU",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "VENDEUR",
      "cni": "110914153",
      "telephone": 695450962,
      "matricule": 172,
      "photo": ""
    },
    {
      "id": 152,
      "dateCreation": null,
      "nom": "NGUETOUO",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 153,
      "dateCreation": null,
      "nom": "DOUANLA JACQUELINE",
      "sexe": "F",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 154,
      "dateCreation": null,
      "nom": "ELOUNDOU INNOCENT",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 155,
      "dateCreation": null,
      "nom": "FORCHIA RENE",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 156,
      "dateCreation": null,
      "nom": "FOTSO EVARISTE L",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 157,
      "dateCreation": null,
      "nom": "GUEPI NAFACK BRANDON",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 158,
      "dateCreation": null,
      "nom": "GUESSAS KENFACK AURELOIS",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "162324",
      "telephone": 690132041,
      "matricule": 151,
      "photo": ""
    },
    {
      "id": 159,
      "dateCreation": null,
      "nom": "GUESSAS KENFACK PATRICIA",
      "sexe": "F",
      "localisation": "MARCHE MENDONG",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 160,
      "dateCreation": null,
      "nom": "JOGO SERGES",
      "sexe": "M",
      "localisation": "",
      "activite": "",
      "cni": "",
      "telephone": null,
      "matricule": null,
      "photo": ""
    },
    {
      "id": 161,
      "dateCreation": null,
      "nom": "KAGOU BENNEDY",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "MENUISIER",
      "cni": "KIT 329",
      "telephone": 699893650,
      "matricule": 1063,
      "photo": ""
    },
    {
      "id": 162,
      "dateCreation": null,
      "nom": "KENNE ARMEL",
      "sexe": "M",
      "localisation": "MARCHE MENDONG",
      "activite": "ESTETHICIEN",
      "cni": "100728475",
      "telephone": 656308666,
      "matricule": 1115,
      "photo": ""
    },
    {
      "id": 163,
      "dateCreation": 44431,
      "nom": "YOUBANG FAMBOUO VIDAL",
      "sexe": "M",
      "localisation": "CHAPELLE TKC",
      "activite": "",
      "cni": "",
      "telephone": 695141531,
      "matricule": null,
      "photo": ""
    }
   ]);

  getCompte(){
    return this.compte$.asObservable();
  }
  getClients(){
    return this.clients$.asObservable();
  }

  constructor() { }

  addClient(client: any, photo: AppPhoto){
    const clients = [{...client, photo: photo.cropped}, ...this.clients$.getValue()];
    this.clients$.next(clients);
  }

  versement(amount: number){  
    const d = new Date();
    const versement = {
      title: 'Versement',
      date: d.toDateString(),
      amount: amount,
      type: 'credit',
      currency: 'XAF',
    };

    var compte = this.compte$.getValue();
    var solde = 0;
    compte.transactions.forEach(t => {
      solde += t.amount;
    });

    const newCompte = {
      ...compte,
      solde : solde,
      transactions: [versement, ...compte.transactions]
    }

    this.compte$.next(newCompte);
  }
}
